### ISSUE TITLE
ractive-legacy-0.7.2 does not work in IE8

### ISSUE THREAD

**Issue by paul-bjorkstrand** [ractivejs/ractive#1908]
Errors occur, at minimum caused by `return template.textContent;` in `function fromId(id, options)`, but i feel there may be other errors, as well.

**Comment by Rich-Harris** [comment]
Ah, thanks, that's useful - there were some reports on #1579 to the same effect, but now we know what's causing it. (Though searching through the issue history, it turns out @Eric013 already flagged it up (https://github.com/ractivejs/ractive/pull/1839#commitcomment-10484585) and we missed it - sorry Eric!)

**Comment by Rich-Harris** [comment]
@paul-bjorkstrand I've raised a PR (#1914) that should fix this in theory. The odd thing is that I wasn't able to reproduce it locally (running IE8 on a Win7 VM via VirtualBox), regardless of browser/document mode.

Could you try replacing `return template.textContent;` with this...

```js
return ( 'textContent' in template ? template.textContent : template.innerText );
```

...and let us know if that fixes the problem? If so, we can merge #1914 and close this. Thanks

**Comment by paul-bjorkstrand** [comment]
No good, I seem to have success with
```js
return ( 'textContent' in template ? template.textContent : template.innerHTML );
```
I think there is a problem on with innerTextl it returns empty string for all of my templates.

According to [MDN's documentation for textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Differences_from_innerText) innerText is style-aware whereas textContent is not.

My suggestion is then to use innerHTML instead.

**Comment by paul-bjorkstrand** [comment]
Still not working, but I believe it is due to how innerText works. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Differences_from_innerText) innerText is style-aware where textContent is not. For my case, the Ractive template is inside an (initially) hidden modal. This causes the innerText to return an empty string.

Although I do understand the reasoning from moving away from innerHTML (XSS attack) it all but makes Ractive for IE8 worthless. I suggest that if you plan on keeping IE8 support, you find a better shim or stick with innerHTML. Someday, IE8 will only be a distant memory...

**Comment by Rich-Harris** [comment]
@paul-bjorkstrand I've updated and merged #1914 to use `innerHTML` instead of `innerText` - good catch, I didn't realise it was style-aware. It'll be released in 0.7.3: https://github.com/ractivejs/ractive/pull/1931
