### ISSUE TITLE
Class properties are not present when creating component using <MyComponent/> syntax

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3362]
## Description:
When using "class based component" which are added to the page using `<MyComponent/>` syntax, it seems that properties added inside the class are not set. 
Maybe is related to the fact that the constructor is not called.

These issues are not present when component is created using `new  MyComponent()`.

## Versions affected:
- 1.3.13
- edge

## Platforms affected:
All

## Reproduction:
1. Open this [fiddle](https://jsfiddle.net/unbmf90c/)
2. Check the console
    - Only 1 constructor log is present
3. Click on "Using HTML syntax" buttons
   - Error logs appears
4. Click on "Using new" buttons
   - Everything works as expected

When clicking 

```javascript
function sharedFunction() {
  console.info('inside sharedFunction');
}

class MyComponent extends Ractive {
  sharedFunction = sharedFunction;
  
  customProperty = [];

  constructor(opts) {
    super(opts);
    
    console.info('constructor');
  }
}

Ractive.extendWith(MyComponent, {
  template: `
  Testing
  <button on-click="property">property</button>
  <button on-click="function">function</button>
  `,
  
  on: {
    property() {
      this.customProperty.push('prova');
      console.info(this.customProperty);
    },
    function() {
      this.sharedFunction();
    }
  }
})

Ractive.components.MyComponent = MyComponent;

const r = window.r = new Ractive({
  el: '#main',
  template: `
  <MyComponent></MyComponent>
  `,
});

const usingNew = new MyComponent({ el: '#using-new' });
```

**Comment by evs-chris** [comment]
Ractive is a little weird on construction, but I think I have a solution for this. If Travis agrees, it should be fixed on edge shortly.

**Comment by marcalexiei** [comment]
Hi Chris,
it seems that issue is not resolved 😭. 

I updated the [fiddle](https://jsfiddle.net/qnyLcmj4/) pointing to the last build (`1.4.0-build-46`):

Now there is a TypeError: `Cannot call a class constructor without |new|`.

You can also find a reproduction repo [here](https://github.com/marcalexiei/ractive-sandbox#class-props). 
See `class props` section.

**Comment by evs-chris** [comment]
Ah, yeah, transpiler got me, as it turned the class into a plain old-school prototypal class. I think I have a slightly different tack that will work, and travis will be chewing on it shortly.

**Comment by marcalexiei** [comment]
Now class instance is correctly populated with all attributes.

Thank you very much!
